---
  - name: lets try some docker
    apt: pkg={{item}} state=present update_cache=yes 
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: add gpg keys
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

  - name: add repo
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present

  - name: remove old repo
    apt: pkg=lxc-docker state=absent update_cache=yes
    
  - name: install docker
    apt: pkg=docker-engine state=present

  - name: install docker-compose dependency
    apt: pkg={{item}} state=present
    with_items:
      - python-dev
      - libxml2-dev
      - libxslt-dev
      - python-pip

  - name: lets install the very useful docker-compose
    pip: name=docker-compose state=present
